version: '3.8'

services:
  backend:
    build: .
    container_name: synthetic-exchange-backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./test.db:/app/test.db
    environment:
      - DATABASE_URL=sqlite:///./test.db
    restart: unless-stopped

  frontend:
    build: ./synthetic-ui
    container_name: synthetic-exchange-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  data:
  database: